
volumes:
    logs:
        driver: local
services:
    slim:
        container_name: slim_container
        image: sigurdne/portico_estate_webserver:latest
        working_dir: /var/www/html
        environment:
            docker: "true"
        ports:
            - "8088:80"
        volumes:
            - .:/var/www/html
            - ./logs:/var/log/apache2
 