version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build: 
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8088
        environment:
            docker: "true"
        ports:
            - "8088:8088"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
